START TRANSACTION;

DROP TABLE IF EXISTS media_item;
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS media_type;
DROP TABLE IF EXISTS fee;
DROP TABLE IF EXISTS fee_status;
DROP TABLE IF EXISTS `transaction`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS membership_type;
DROP TABLE IF EXISTS account_status;

COMMIT;